# Generated by Django 4.0.8 on 2022-11-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('P', 'Portuguese'), ('S', 'Spanish'), ('E', 'English')], max_length=1)),
            ],
        ),
    ]
