base_url = "https://docs.cordstart.com"
title = "Docs:CordStart"
description = "Building something cool."
output_dir = "docs"
compile_sass = false # Tailwind v4 handles CSS

[extra]
project_gh = "https://docs.cordstart.com"
author_name = "Jorge Alarcon"

